version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.19
jobs:
  aws-cli:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup: {}
      - run: aws --version
workflows:
  version: 2
  aws-cli:
    jobs:
      - aws-cli: {}