version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.19
jobs:
  aws-cli:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          configure-default-region: false
      - run:
          name: Deploy CloudFront
          command: |
            aws cloudformation deploy --region us-east-1 \
                               --template-file cloudformation-template.yml \
                               --stack-name compliment-it-site \
                               --parameter-overrides \
                                  "HostedZoneName=compliment.it." \
                                  "WebsiteAddress=compliment.it" \
                                  "S3BucketName=compliment-it-site" \
                                  "TlsCertificateArn=arn:aws:acm:us-east-1:204244381428:certificate/979e3816-42f5-4751-9647-2646808a4317"
      - run:
          name: Upload Site
          command: |
            aws s3 sync site s3://compliment-it-site

workflows:
  version: 2
  aws-cli:
    jobs:
      - aws-cli: {}